Joan_DynamicComment/ViewComponents/FooterViewComponent.cs
using System;
using Joan_DynamicComment.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Joan_DynamicComment.ViewComponents
{
	public class FooterViewComponent:ViewComponent
	{
		private readonly AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        
		public async Task<IViewComponentResult> InvokeAsync()
		{

			return View(await _context.NavBars.ToDictionaryAsync(n => n.Key,n=>n.Value)) ;
		}
	}
}

Joan_DynamicComment/ViewComponents/HeaderViewComponent.cs
using System;
using Joan_DynamicComment.DAL;
using Joan_DynamicComment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Joan_DynamicComment.ViewComponents
{
	public class HeaderViewComponent:ViewComponent
	{
		private readonly AppDbContext _context;
		private readonly UserManager<AppUser> _userManager;
        public HeaderViewComponent(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
			_userManager = userManager;
        }

       
		public async Task<IViewComponentResult> InvokeAsync()
		{
			

            if (User.Identity.IsAuthenticated)
			{
                ViewBag.User = await _userManager.FindByNameAsync(User.Identity.Name);
            }
			return View(await _context.NavBars.FirstOrDefaultAsync());
		}
	}
}

Joan_DynamicComment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<!-- Mirrored from demo.hasthemes.com/juan-preview-v1/juan/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 07 Mar 2021 22:36:22 GMT -->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="meta description" />
    <title>@ViewBag.Title</title>
    <!--=== Favicon ===-->
    <link rel="shortcut icon"
          href="~/assets/img/favicon.ico"
          type="image/x-icon" />
    <link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
    <!--=== All Plugins CSS ===-->
    <link href="~/assets/css/plugins.css" rel="stylesheet" />
    <!--=== All Vendor CSS ===-->
    <link href="~/assets/css/vendor.css" rel="stylesheet" />
    <!--=== Main Style CSS ===-->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    @RenderSection("CostumStyles", false);
    <!-- Modernizer JS -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  @await Component.InvokeAsync("Header");
    <main>
        @RenderBody()
    </main>
    <!-- main wrapper end -->
    <!-- Quick view modal start -->
    <div class="modal" id="quick_view">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <!-- product details inner end -->
                    <div class="product-details-inner">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="product-large-slider mb-20">
                                    <div class="pro-large-img img-zoom">
                                        <img src="~/assets/img/product/product-details-img1.jpg"
                                             alt="product thumb" />
                                    </div>
                                    <div class="pro-large-img img-zoom">
                                        <img src="~/assets/img/product/product-details-img2.jpg"
                                             alt="product thumb" />
                                    </div>
                                    <div class="pro-large-img img-zoom">
                                        <img src="~/assets/img/product/product-details-img3.jpg"
                                             alt="product thumb" />
                                    </div>
                                    <div class="pro-large-img img-zoom">
                                        <img src="~/assets/img/product/product-details-img4.jpg"
                                             alt="product thumb" />
                                    </div>
                                </div>
                                <div class="pro-nav slick-row-5">
                                    <div class="pro-nav-thumb">
                                        <img src="~/assets/img/product/product-details-img1.jpg"
                                             alt="" />
                                    </div>
                                    <div class="pro-nav-thumb">
                                        <img src="~/assets/img/product/product-details-img2.jpg"
                                             alt="" />
                                    </div>
                                    <div class="pro-nav-thumb">
                                        <img src="~/assets/img/product/product-details-img3.jpg"
                                             alt="" />
                                    </div>
                                    <div class="pro-nav-thumb">
                                        <img src="~/assets/img/product/product-details-img4.jpg"
                                             alt="" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-7">
                                <div class="product-details-des">
                                    <h3 class="pro-det-title">Primitive Mens Premium Shoes</h3>
                                    <div class="pro-review">
                                        <span><a href="#">1 Review(s)</a></span>
                                    </div>
                                    <div class="price-box">
                                        <span class="regular-price">$70.00</span>
                                        <span class="old-price"><del>$80.00</del></span>
                                    </div>
                                    <p>
                                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
                                        sed diam nonumy eirmod tempor invidunt ut labore et dolore
                                        magna aliquyam erat, sed diam voluptua.
                                    </p>
                                    <div class="quantity-cart-box d-flex align-items-center mb-20">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                                <input type="text" value="1" />
                                            </div>
                                        </div>
                                        <a href="cart.html" class="btn btn-default">Add To Cart</a>
                                    </div>
                                    <div class="availability mb-20">
                                        <h5 class="cat-title">Availability:</h5>
                                        <span>In Stock</span>
                                    </div>
                                    <div class="share-icon">
                                        <h5 class="cat-title">Share:</h5>
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-pinterest"></i></a>
                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- product details inner end -->
                </div>
            </div>
        </div>
    </div>
    <!-- Quick view modal end -->
    <!-- Start Footer Area Wrapper -->
   @await Component.InvokeAsync("Footer")
    <div class="offcanvas-search-wrapper">
        <div class="offcanvas-search-inner">
            <div class="offcanvas-close">
                <i class="ion-android-close"></i>
            </div>
            <div class="container">
                <div class="offcanvas-search-box">
                    <form class="d-flex bdr-bottom w-100">
                        <input type="text" placeholder="Search entire storage here..." />
                        <button class="search-btn">
                            <i class="ion-ios-search-strong"></i>search
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- offcanvas search form end -->
    <!-- offcanvas mini cart start -->
    <div class="offcanvas-minicart-wrapper">
        <div class="minicart-inner">
            <div class="offcanvas-overlay"></div>
            <div class="minicart-inner-content">
                <div class="minicart-close">
                    <i class="ion-android-close"></i>
                </div>
                <div class="minicart-content-box">
                    <div class="minicart-item-wrapper">
                        <ul>
                            <li class="minicart-item">
                                <div class="minicart-thumb">
                                    <a href="product-details.html">
                                        <img src="~/assets/img/cart/cart-1.jpg" alt="product" />
                                    </a>
                                </div>
                                <div class="minicart-content">
                                    <h3 class="product-name">
                                        <a href="product-details.html">Flowers bouquet pink for all flower lovers</a>
                                    </h3>
                                    <p>
                                        <span class="cart-quantity">1 <strong>&times;</strong></span>
                                        <span class="cart-price">$100.00</span>
                                    </p>
                                </div>
                                <button class="minicart-remove">
                                    <i class="ion-android-close"></i>
                                </button>
                            </li>
                            <li class="minicart-item">
                                <div class="minicart-thumb">
                                    <a href="product-details.html">
                                        <img src="~/assets/img/cart/cart-2.jpg" alt="product" />
                                    </a>
                                </div>
                                <div class="minicart-content">
                                    <h3 class="product-name">
                                        <a href="product-details.html">Jasmine flowers white for all flower lovers</a>
                                    </h3>
                                    <p>
                                        <span class="cart-quantity">1 <strong>&times;</strong></span>
                                        <span class="cart-price">$80.00</span>
                                    </p>
                                </div>
                                <button class="minicart-remove">
                                    <i class="ion-android-close"></i>
                                </button>
                            </li>
                        </ul>
                    </div>

                    <div class="minicart-pricing-box">
                        <ul>
                            <li>
                                <span>sub-total</span>
                                <span><strong>$300.00</strong></span>
                            </li>
                            <li>
                                <span>Eco Tax (-2.00)</span>
                                <span><strong>$10.00</strong></span>
                            </li>
                            <li>
                                <span>VAT (20%)</span>
                                <span><strong>$60.00</strong></span>
                            </li>
                            <li class="total">
                                <span>total</span>
                                <span><strong>$370.00</strong></span>
                            </li>
                        </ul>
                    </div>

                    <div class="minicart-button">
                        <a href="cart.html"><i class="fa fa-shopping-cart"></i> view cart</a>
                        <a href="cart.html"><i class="fa fa-share"></i> checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- offcanvas mini cart end -->
    <!-- Scroll to top start -->
    <div class="scroll-top not-visible">
        <i class="fa fa-angle-up"></i>
    </div>
    <!-- Scroll to Top End -->
    <!--=======================Javascript============================-->
    <!--=== All Vendor Js ===-->
    <script src="~/assets/js/modernizr-2.8.3.min.js"></script>
    <script src="~/assets/js/vendor.js"></script>
    <!--=== All Plugins Js ===-->
    <script src="~/assets/js/plugins.js"></script>
    <!--=== Active Js ===-->
    <script src="~/assets/js/active.js"></script>
    @RenderSection("CostumScripts", false);
</body>

<!-- Mirrored from demo.hasthemes.com/juan-preview-v1/juan/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 07 Mar 2021 22:36:53 GMT -->
</html>